version: '2'
services:
  mydatabase:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: jfrogchina
      MYSQL_DATABASE: wchat
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  demo:
    image: docker-release-local.demo.jfrogchina.com/rancher-demo:12
    stdin_open: true
    tty: true
    links:
    - mydatabase:database
    ports:
    - 8081:8081/tcp
    labels:
      io.rancher.container.pull_image: always

